kind: Deployment
apiVersion: apps/v1
metadata:
  name: qotd-backend
  labels:
    app: qotd-backend
    sandbox: learn-kubernetes
    learn-kubernetes: quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qotd-backend
  template:
    metadata:
      labels:
        app: qotd-backend
    spec:
      containers:
        - name: quotes
          image: quay.io/rhdevelopers/quotes:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 10000
              protocol: TCP
