kind: Deployment
apiVersion: apps/v1
metadata:
  name: qotd-frontend
  labels:
    app: qotd-frontend
    sandbox: learn-kubernetes
    learn-kubernetes: quotesweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qotd-frontend
  template:
    metadata:
      labels:
        app: qotd-frontend
    spec:
      containers:
        - name: quotes
          image: quay.io/rhdevelopers/quotesweb:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
