apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: qotd-frontend
    sandbox: learn-kubernetes
    learn-kubernetes: quotesweb
  name: qotd-frontend
spec:
  port:
    targetPort: 3000-tcp
  to:
    kind: Service
    name: qotd-frontend
