apiVersion: v1
kind: Service
metadata:
  labels:
    app: qotd-frontend
    sandbox: learn-kubernetes
    learn-kubernetes: quotesweb
  name: qotd-frontend
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: qotd-frontend
  sessionAffinity: None
  type: ClusterIP
